#!/usr/bin/env bash

# Build version of TiddlyWiki with external javascript
# Usage:
#  bldxjs

DEST=$PWD
RECIPE_EXT_JS=$PWD/tiddlywiki_externaljs.html.recipe
RECIPE=$PWD/tiddlywiki.html.recipe
ruby -Ku -C ../tools/cooker cook.rb $RECIPE -o twcore.js -d$DEST -q -j $2 $3 $4 $5
ruby -Ku -C ../tools/cooker cook.rb $RECIPE_EXT_JS -d$DEST -q $2 $3 $4 $5
